#
###################################
# Site wide configuration
####################################
#
title: Duncan's Ramblings
email: duncan.deltoro@gmail.com
description: InfoSec Professional
url: 


#
###################################
# Jekyll configuration
####################################
#
timezone:          UTC
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Duncan del Toro"
  avatar: avatar.png
  job: "The Ramblings of an InfoSec Professional"
  bio: "Asundry InfoSec related topics and walkthroughs"
  email: duncan.deltoro@gmail.com
  disqus-shortname:
  twitter: ddeltoro42
  facebook: #username
  google:
    plus: #username
    analytics: UA-84491507-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: m4ng0n3l
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: duncandeltoro
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
